In [2]:
help('keywords')



Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [3]:
from keyword import kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [ ]:
# identifier
#keyword
#operators
       # 1. arithmetics: +,-,*,/,**,//,%%
       # 2.relational: ==,!=,>,<,<=,>=
       # 3.assignment: =,+=,-=,*=
       # 4. logical: and,or,not
       # 5.membership: in, not in
       # 6.bitwise: &,!,^,~,<<,>>
       # 7.identify: is,is not
 # data type / data classes
  # numeric: int,float,complex
  # sequence: 
  #             str: immutable collection of character ' "" '
  #          []   list: mutable & unstructured coll of het elements
  #          ()  tuple: immutable & unstructured coll of het elements
  # Mapping:
  #   {} dict: mutable & unstructured coll of key- value pairs
  # set:
  # {}  set: unordered coll of unique item
  # boolean:
  # bool: true ,false
# empty data :
    #None type: None
# data operations
  # 1. item accessing( indexing/slicing/subscripting)
  # 2 .item insertion
  # 3.item assignment( possible with mutable only)  
  # 4.item deletiom( possible with mutable only) 
 #data type built in functions
   #str: upper,lower,find ,split,strip,join,format,count
   # list: append,sort, count,copy, insert, remove,index,pop
   # tuple: count ,index
   # dict : keys ,values,update,get,pop
   # set: add,difference,union,pop,remove  

In [5]:
t=[2,3,4]
type(t)

list

In [6]:
print(t)


[2, 3, 4]


In [7]:
len(t)

3

In [8]:
s='my name is NJ'
s[0]


'm'

In [9]:
len(s)


13

In [10]:
# slicing s[start : stop(not included) : steosize]
###### s[0 : end :+1]
###### s[ end : 0: -ve]
s[2:8:1]


' name '

In [11]:
s[-8:2:1]


''

In [12]:
s[-9:]


'ame is NJ'

In [13]:
s='a sample python statement'
s

'a sample python statement'

In [14]:
s[-11:-17:-1]


'nohtyp'

In [15]:
s[-9:]


'statement'

In [16]:
s[:-10:1]

'a sample python'

In [17]:
s[::-1]

'tnemetats nohtyp elpmas a'

In [22]:
t=[1,2,3,4,5]
len(t)

5

In [24]:
type(t)


list

In [25]:
d={'a':34,'b':45}


In [27]:
d['b']


45

In [ ]:
d1 = [{'a':34},66,{'66':[{'00':[98,'hi']},'awesome',{'m':'n'}]}]

In [2]:
s='468hi3.4'
a= [4,6,8,'hi',3.4]
b= (4,6,8,'hi',3.4)
c={4:6,8:['hi',3.4]}
d= {4,6,8,'hi',3.4}


In [3]:
type(s),type(a),type(b),type(c),type(d)

(str, list, tuple, dict, set)

In [4]:
len(s),len(a),len(b),len(c),len(d)

(8, 5, 5, 2, 5)

In [5]:
# for concatenation apply only on # str,list,tuple
'hi'+'k'

'hik'

In [6]:
[4,5]+[6,7]

[4, 5, 6, 7]

In [7]:
(3,4)+(6,7)

(3, 4, 6, 7)

In [8]:
'hi'*8

'hihihihihihihihi'

In [9]:
s+='k'
s

'468hi3.4k'

In [10]:
s[:3]

'468'

In [11]:
s[3:]

'hi3.4k'

In [13]:
s= s[:3] + 'jai shree ram' + s[3:]
s

'468jai shree ramhi3.4k'

In [14]:
a


[4, 6, 8, 'hi', 3.4]

In [16]:
a +=['bye']
a

[4, 6, 8, 'hi', 3.4, 'bye', 'bye']

In [17]:
a = a[:2] +[39] + a[2:]
a

[4, 6, 39, 8, 'hi', 3.4, 'bye', 'bye']

In [18]:
b

(4, 6, 8, 'hi', 3.4)

In [19]:
m=('bye',)
type(m)

tuple

In [20]:
m=('bye')
type(m)

str

In [21]:
b

(4, 6, 8, 'hi', 3.4)

In [23]:
b +=('bye',)
b

(4, 6, 8, 'hi', 3.4, 'bye', 'bye')

In [24]:
(*a,*b) # for addition tuple and list

(4, 6, 39, 8, 'hi', 3.4, 'bye', 'bye', 4, 6, 8, 'hi', 3.4, 'bye', 'bye')

In [25]:
(*a,*b,*s)  # use of args and kargs

(4,
 6,
 39,
 8,
 'hi',
 3.4,
 'bye',
 'bye',
 4,
 6,
 8,
 'hi',
 3.4,
 'bye',
 'bye',
 '4',
 '6',
 '8',
 'j',
 'a',
 'i',
 ' ',
 's',
 'h',
 'r',
 'e',
 'e',
 ' ',
 'r',
 'a',
 'm',
 'h',
 'i',
 '3',
 '.',
 '4',
 'k')

In [26]:
c

{4: 6, 8: ['hi', 3.4]}

In [27]:
c[99] = [98,'ek number'] # for addition of dictionary
c

{4: 6, 8: ['hi', 3.4], 99: [98, 'ek number']}

In [28]:
c2 ={'a':45,'b':34}
print(c)
print(c2)

{4: 6, 8: ['hi', 3.4], 99: [98, 'ek number']}
{'a': 45, 'b': 34}


In [29]:
{**c,**c2}  # (*args,**kwargs)

{4: 6, 8: ['hi', 3.4], 99: [98, 'ek number'], 'a': 45, 'b': 34}

In [30]:
s

'468jai shree ramhi3.4k'

In [31]:
# item assignment
#s[0] ='a' # not possible
#a[0] ='a' #done
#b[0] = 'a' #not poosible
#c[4] = 99 #done
 

 #item deletion
  # del s[0] #not possible
  # del a[0] # possible
  # del b[0] #not possible
  # del c[4] # possible

TypeError: 'str' object does not support item assignment

In [ ]:
# item assignment
#s[0] ='a' # not possible
#a[0] ='a' #done
#b[0] = 'a' #not poosible
#c[4] = 99 #done
 

 #item deletion
  # del s[0] #not possible
  # del a[0] # possible
  # del b[0] #not possible
  # del c[4] # possible

In [33]:
del a[0]
a

[6, 39, 8, 'hi', 3.4, 'bye', 'bye']

In [34]:
True

True

In [35]:
False

False

In [36]:
bool('False') # bracket ma string hai

True

In [46]:
print(bool(' ')),
bool([]),
bool({})
bool(())
bool(-1)
bool(45)
bool([()],)

True


True

In [6]:
a= 34
b=34.5
c=34+5j
d='hello'
e=[3,4,5]
f=(3,4,5)
g={3:[4,5]}
h={3,4,5}

In [40]:
d

'hello'

In [41]:
d.upper() 

'HELLO'

In [4]:
d


NameError: name 'd' is not defined

In [5]:
s

NameError: name 's' is not defined

In [7]:
s

NameError: name 's' is not defined

In [8]:
d

'hello'

In [9]:
d.find('o')

4

In [12]:
d.split('el')
d

'hello'

In [13]:
'-'.join('wars')

'w-a-r-s'

In [14]:
'#'.join ('hi this is a new string'.split())

'hi#this#is#a#new#string'

In [15]:
'hi this is a new string'.replace(' ','#')

'hi#this#is#a#new#string'

In [16]:
d.count('l')

2

In [18]:
x= 20
y=30
# z = 'ek aisa data  jo 20 to 30 hai'
# format specifier

z = 'ek aisa data  jo %d to %d hai'%(x,y)
z

'ek aisa data  jo 20 to 30 hai'

In [21]:
# using format function
z= 'ek aisa data  jo {} to {} hai'
z= z.format(x,y)
z


'ek aisa data  jo 20 to 30 hai'

In [24]:
# 'ek aisa data  jo 20 to 30 hai lekin 20 hi kaffi haai
z1='ek aisa data  jo {0} to {1} hai lekin {0} hi kaafi haai'
z1= z1.format(x,y)
z1

'ek aisa data  jo 20 to 30 hai lekin 20 hi kaafi haai'

In [27]:
# using f string 
f'anything'

zf=f'ek aisa data  jo {x} to {y} hai lekin {x} hi kaafi haai'
zf


'ek aisa data  jo 20 to 30 hai lekin 20 hi kaafi haai'

In [29]:
# e.append('somedata')
# input arg but not output args
e.append(45)
e

[3, 4, 5, 45, 45]

In [30]:
# no input arg but output args there
d.upper()

'HELLO'

In [31]:
e.count(4)

1

In [37]:
e.insert(2,1000)
e

[3, 4, 1000, 5, 45, 45]

In [38]:
e.remove(1000)
e

[3, 4, 5, 45, 45]

In [39]:
help(e.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Sort the list in ascending order and return None.
    
    The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
    order of two equal elements is maintained).
    
    If a key function is given, apply it once to each list item and sort them,
    ascending or descending, according to their function values.
    
    The reverse flag can be set to sort in descending order.



In [40]:
e.sort(reverse=True)
e

[45, 45, 5, 4, 3]

In [41]:
e.reverse
e

[45, 45, 5, 4, 3]

In [42]:
e1 =['hi','wow','good','bad']
e1

['hi', 'wow', 'good', 'bad']

In [43]:
len(e1[0])

2

In [44]:
e1.sort(key=len)
e1

['hi', 'wow', 'bad', 'good']

In [45]:
e1.sort(key=len,reverse=True)
e1

['good', 'wow', 'bad', 'hi']

In [46]:
f1= list(f)
f1.sort(reverse=True)
f1=tuple(f1)
f1

(5, 4, 3)

In [47]:
tuple(sorted(f,reverse=True))

(5, 4, 3)

In [49]:
k= e.pop()
e

[45, 45, 5]

In [50]:
g

{3: [4, 5]}

In [51]:
g.keys()

dict_keys([3])

In [52]:
type(g.keys())

dict_keys

In [53]:
list(g.keys())[0]   # type casting into list

3

In [56]:
g.get('z','oh no')


'oh no'

In [57]:
g.get('z') # give null values

In [58]:
e3 =  e
e3

[45, 45, 5]

In [60]:
e3.append(60)
e

[45, 45, 5, 60, 60]

In [61]:
e

[45, 45, 5, 60, 60]

In [66]:
help(e.copy)

Help on built-in function copy:

copy() method of builtins.list instance
    Return a shallow copy of the list.



In [64]:
e4= e.copy()
e4.append(8)
e4

[45, 45, 5, 60, 60, 8]

In [67]:
p = [3,8,2,4,6,35,6,3,67,6,35,7,4,6,46,68]
p1 = set(p)
p1

{2, 3, 4, 6, 7, 8, 35, 46, 67, 68}

In [68]:
p1.add(23)
p1

{2, 3, 4, 6, 7, 8, 23, 35, 46, 67, 68}

In [ ]:
# actual programming
#    logics
# condition
# loops
# errors
# function
# classes
#  library

In [72]:
# suites in python
# syntax
 
#   statement1:
#       content
#       content
# statement2:
#       content
#  statement3:
#       more content




a= 10
if (a>5):
    print("or ya toh bada ha")
    if(a<100):
        print("ya bhi thhek hai")
    print('ya hogya')
elif (a<-20):
    print('ya bhi theel ha')
else:
    print("ya theek ha")
print('the end')    

or ya toh bada ha
ya bhi thhek hai
ya hogya
the end


In [ ]:
#  conditional statement
#        if-else-if
# looping 
#        while-else
#  for-else
#       continue/break
#  error handling
#       try-except-else-fianlly
#  user defined function
#       def
#  classes
#       class

In [73]:
a=20
while a>0:
    print('hello',a)
    a-=3
    if ( a==11):
        break
    if (a<10):
        continue
    print('one more')

hello 20
one more
hello 17
one more
hello 14


In [74]:
a=20
while a>0:
    print('hello',a)
    a-=3
    if ( a==11):
        break
    print('one more')
else:
    print('acha chalta hu')

hello 20
one more
hello 17
one more
hello 14


In [2]:
#  for _ each
for i in 'hello':
    print(i, '*')


h *
e *
l *
l *
o *


In [6]:
for i  in range(1,11): 
    print(i,'*')

1 *
2 *
3 *
4 *
5 *
6 *
7 *
8 *
9 *
10 *


In [ ]:
for_each
for object in collection:
    pass

In [8]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
a=[4,'hi','nice',35]
b=[]
for val in a:
    b.append(val*2)
b

[8, 'hihi', 'nicenice', 70]

In [12]:
a=[4,'hi','nice',35]
b=[]
for i in range(len(a)):
    b.append(a[i]*2)
b

[8, 'hihi', 'nicenice', 70]

In [13]:
#  comprehension
# # for_loop statement which are of one linear
#  list comprehension 
#     [ output for _ loop] - map
#        [ output for _ loop if_condition] -filter

# dictionar compr
#  { key_op:value_op for-loop}

#  set compr
    # { output for _loop}

    
# generator compr
#   (output for_loop)



b=[val*2 for val in a]
b

[8, 'hihi', 'nicenice', 70]

In [14]:
k=[4,7,3,67,2,4,45,22,11,9,8]


In [15]:
p=[val for val in k if val %2==0]
p

[4, 2, 4, 22, 8]

In [28]:
[val for val in k if not val % 2 and val > 10]



[]

In [29]:
[val for val in k if not val % 2 and val > 10]

[]

In [30]:
k

[]

In [31]:
k=[4,7,3,67,2,4,45,22,11,9,8]

In [32]:
k

[4, 7, 3, 67, 2, 4, 45, 22, 11, 9, 8]

In [33]:
[val for val in k if not val % 2 and val > 10]

[22]

In [37]:
p=[]
for val in k:
        if val%2==0:
            p.append(val // 2)
        else:
            p.append(val * 2)
p


[2, 14, 6, 134, 1, 2, 90, 11, 22, 18, 4]

In [38]:
#  a>5? ye kar dena: nahi toh ya wala kar dena
#   ye kar dena if-cond else ya wala kar dena

In [39]:
#  task: multiply by 2 if odd otherwise check if it
#  is less than 20 then do // 2 otherwise do not anything

In [41]:
p=[val * 2 if val% 2 ==1 else val//2 for val in k]
p

[2, 14, 6, 134, 1, 2, 90, 11, 22, 18, 4]

In [42]:
[
    val * 2 if val% 2 ==1 else val//2 if val< 20 else val
    for val in k
]

[2, 14, 6, 134, 1, 2, 90, 22, 22, 18, 4]

In [43]:
m= {val: val**2 for val in k if val% 2==0}
m

{4: 16, 2: 4, 22: 484, 8: 64}

In [44]:
for i in m:
    print(i)

4
2
22
8


In [48]:
for i,j in m.items():
    print(j,i)

16 4
4 2
484 22
64 8


In [50]:
#  user defined function

def function_ka_naam():
    '''
    jai shree ram
    '''
    print('ye kuch kar dega')

In [51]:
function_ka_naam()

ye kuch kar dega


In [ ]:
# a=10
# while a>5:
#     pass
# print('ji')

In [52]:
def ekor(ekvalue,dusrivalue):
    return ekvalue * dusrivalue

In [53]:
ekor(4,5)

20

In [55]:
def merimarzi(ekvalue,dusrivalue):
    return (ekvalue * dusrivalue) + ekvalue 

In [56]:
merimarzi(dusrivalue=10,ekvalue=12)

132

In [57]:
def merimarzi(ekvalue,dusrivalue,teesra):
    return (ekvalue * dusrivalue) + ekvalue -teesra

In [58]:
merimarzi(12,34,dusrivalue=10)

TypeError: merimarzi() got multiple values for argument 'dusrivalue'

In [59]:
def kuchor(x=10,*v):
    return[i*x for i in v]

In [60]:
kuchor(3,6,8)

[18, 24]

In [61]:
def kuchor(x=10,*v,**u):
    return[i*x for i in v],u

In [62]:
kuchor(3,6,8)

([18, 24], {})

In [63]:
kuchor(3,6,8,somedata= [3,4,5,6])

([18, 24], {'somedata': [3, 4, 5, 6]})

In [ ]:
# pyhton function can be
# 1.Assigned as a value
# 2.taken as input argument in another function
# defined inside another function
#  return  a function as output from another function

In [1]:
def abc():
    print('hi')

In [2]:
abc()

hi


In [3]:
k =abc

In [4]:
k

<function __main__.abc()>

In [5]:
k()

hi


In [6]:
# for 2 point
def xyz(f):
    f()

In [7]:
xyz(k)

hi


In [8]:
xyz (f=abc)

hi


In [9]:
def pqr():
    def qrp():
        print('hello')
    qrp()
pqr()        

hello


In [10]:
def pqr():
    def qrp():
        print('hello')
    return qrp

In [11]:
x=pqr
x

<function __main__.pqr()>

In [12]:
#  annonymous Function - Lambda Expression
# Lambda inp_args : output (returned)
 
#  its always one- liner
#  always returns
#   input argument can be multiple,optional,keyword,named,etc
#  output can be simple/conditional/comprehension etc

In [13]:
def doubler(x):
    return x*2
m = doubler(34)
print(m)

68


In [15]:
doubler_L = lambda x : x*2
doubler


<function __main__.doubler(x)>

In [16]:
doubler(34)

68

In [17]:
oddeve = lambda x: 'odd' if x%2 else 'Even'
oddeve(45)

'odd'

In [ ]:
def alag1():
    pass
def alag2():
    pass
def alag3():
    pass

def bada_function():
    step 1
    step 2
    ..

    f(step-10)


    step n

bada_function(lambda x: yaha_pe_alag1)


In [18]:
k = lambda x,y : x*y
k(3,4)

12

In [19]:
k = lambda :3
k()

3

In [ ]:
# scope of variables
# global
# local
# nonlocal
#  

In [20]:
x=10
def abc():
    print(x)
abc()    

10


In [21]:
x=10
def abc():
    x=30
    # print(x)
print(x)
abc()
print(x)

10
10


In [23]:
x=10
def abc():
    global x
    x=30
    # print(x)
print(x)
abc()
print(x)

10
30


In [26]:
x=10
def abc():
    global x
    x=30
    y=15
    def xyz():
        y=28
        print('From xyz',x)
    xyz()
    print(y)

print(x)
abc()
print(x)

10
From xyz 30
28
30


In [27]:
x=10
def abc():
    global x
    x=30
    y=15
    def xyz():
        nonlocal y
        y=28
        print('From xyz',x)
    xyz()
    print(y)

print(x)
abc()
print(x)

10
From xyz 30
28
30


In [ ]:
# working with python modules

In [2]:
!python3 -m pip install numpy
!pip install numpy 

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.


In [3]:
import numpy

In [4]:
#  from , import , as

NameError: name 'keyword' is not defined

In [5]:
import keyword

In [9]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [7]:
from keyword import kwlist

In [ ]:
from keyword import kwlist as 

In [10]:
import numpy as np

In [12]:
a = np.array([])
a

array([], dtype=float64)

In [13]:
b = np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [14]:
len(a)

0

In [15]:
len(b)

5

In [16]:
len(a); len(b) # sirf last ka show karega

5

In [18]:
len(a), len(b)

(0, 5)

In [19]:
a.dtype

dtype('float64')

In [20]:
b.dtype

dtype('int32')

In [21]:
b.shape

(5,)

In [22]:
b.size

5

In [23]:
a.shape

(0,)

In [24]:
a.size

0

In [25]:
a.ndim

1

In [26]:
b.ndim

1

In [27]:
type(a)

numpy.ndarray

In [28]:
c=np.array([[2,3,4],[4,5,6],[7,8,9],[10,11,12]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
c.shape

(4, 3)

In [30]:
d=np.array([[[2],[3],[4]],[[4],[5],[6]],[[7],[8],[9]],[[10],[11],[12]]])
d

array([[[ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [31]:
d.shape

(4, 3, 1)

In [32]:
d=np.array([[[2,20],[3,30],[4,40]],
[[4,40],[5,50],[6,60]],
[[7,70],[8,80],[9,90]],
[[10,100],[11,110],[12,120]]])
d

array([[[  2,  20],
        [  3,  30],
        [  4,  40]],

       [[  4,  40],
        [  5,  50],
        [  6,  60]],

       [[  7,  70],
        [  8,  80],
        [  9,  90]],

       [[ 10, 100],
        [ 11, 110],
        [ 12, 120]]])

In [33]:
d.shape

(4, 3, 2)

In [34]:
c.sum(axis=1)

array([ 9, 15, 24, 33])

In [35]:
c.mean(axis=1)

array([ 3.,  5.,  8., 11.])

In [36]:
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
c[0]

array([2, 3, 4])

In [38]:
c[0][1]

3

In [39]:
c[0:2,-1] # for 1 d array

array([4, 6])

In [40]:
c[0:2,-1:] # for represent in 2d array

array([[4],
       [6]])

In [8]:
import numpy as np


In [10]:
k=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [31]:
m=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [15]:
k[0:5:1,2] # k[start row: end row ma ek add karka likinga: increatment kitna karna ha : coloumn number]

array([ 4,  5, 17,  8])

In [16]:
k[0:5:1,-1]

array([ 4,  5, 17,  8])

k[:,2]

k[:,2]

In [17]:
k[:,2]

array([ 4,  5, 17,  8])

In [18]:
k[:,2].shape

(4,)

In [20]:
k[2:3]

array([[11, 15, 17]])

In [27]:
m[:,-1,:]

array([[ 13, 131]])

In [29]:
m[:,-1:]

array([[[ 13, 131]]])

In [30]:
m.shape

(1, 9, 2)

In [32]:
m.shape

(3, 3, 2)

In [33]:
m[:,-1:]    # initial row: increment: final coloumn

array([[[  7,  71]],

       [[  5,  51]],

       [[ 13, 131]]])

In [34]:
m[1:,1:,:1] # m[1:3:1,1:3:1,0]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [37]:
k+5

TypeError: can only concatenate list (not "int") to list

In [38]:
a[0] =13 # change karni huu index ki value
a

array([13,  6,  5])

In [39]:

del a[0]

ValueError: cannot delete array elements

In [40]:
k

[1, 2, 30]

In [41]:
k=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [42]:
k[0,:] = [30,40,50]
k

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [43]:
k[1,:2]

array([9, 3])

In [44]:
k[:,2] # k [ initial row : ,  konsa colomun number chaiya]

array([50,  5, 17,  8])

In [47]:
k[:,1] = [6,7,8,9]
k

array([[30,  6, 50],
       [ 9,  7,  5],
       [11,  8, 17],
       [19,  9,  8]])

In [48]:
k[:2,1:] = [[101,103],[102,104]]
k

array([[ 30, 101, 103],
       [  9, 102, 104],
       [ 11,   8,  17],
       [ 19,   9,   8]])

In [49]:
np.append(k,[[1,1,1]], axis =0) # zero to add row wise

array([[ 30, 101, 103],
       [  9, 102, 104],
       [ 11,   8,  17],
       [ 19,   9,   8],
       [  1,   1,   1]])

In [57]:
k= np.append(k,[[1],[1],[1]],axis =1)
k

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 3

In [58]:
np.delete(k,3,axis =0)

array([[ 30, 101, 103],
       [  9, 102, 104],
       [ 11,   8,  17],
       [  1,   1,   1],
       [  1,   1,   1]])

In [61]:
k.reshape(6,2)

ValueError: cannot reshape array of size 18 into shape (6,2)

In [67]:
k.reshape(3,6)

array([[ 30, 101, 103,   9, 102, 104],
       [ 11,   8,  17,  19,   9,   8],
       [  1,   1,   1,   1,   1,   1]])

In [65]:
k

array([[ 30, 101, 103],
       [  9, 102, 104],
       [ 11,   8,  17],
       [ 19,   9,   8],
       [  1,   1,   1],
       [  1,   1,   1]])

In [71]:
a1.ktype

NameError: name 'a1' is not defined

In [75]:
a1=np.array([3.5,3,7])
a1
# a1.astype('uint16')

array([3.5, 3. , 7. ])

In [76]:
a1.astype('uint16')

array([3, 3, 7], dtype=uint16)

In [ ]:
# nutshell
# we create arrays
#  1.  np.array()
#  2.  np.zeros()
#  3.  np.arange()
#  4. np.linspace()
#  5 np.random.randint()
#  array have some  attribute and functions

In [77]:
np.random.randint(1,15,[3,4])

array([[13,  6, 10, 10],
       [ 7,  7,  1, 12],
       [10, 14, 10,  7]])

In [1]:
import numpy as np

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.arange(1,11,1) # for int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.linspace(1,10,10) # for float

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.linspace(1,10,10 ,dtype= int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
list(range(1,11,1)) # always for int

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
np.random.randint(1,6,1)

array([5])

In [12]:
np.random.randint(1,6,[4,3,2])

array([[[5, 3],
        [4, 4],
        [2, 2]],

       [[5, 4],
        [5, 4],
        [4, 1]],

       [[5, 5],
        [1, 5],
        [2, 4]],

       [[5, 3],
        [1, 5],
        [3, 2]]])

In [13]:
np.random.randint(31,6000,[4,3])

array([[5006, 2043, 1899],
       [3251, 5200, 5847],
       [5174, 4008, 4902],
       [1675, 1227,  676]])

In [14]:
np.random.seed(10)

In [15]:
np.random.seed(10)
np.random.randint(31,6000,[4,3],)

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [17]:
np.random.seed(50)
np.random.randint(31,6000,[4,3],) # random but stablised

array([[5839, 5631, 1962],
       [2045,  163,  101],
       [3361, 2150,  398],
       [1507, 3053, 3266]])

In [18]:
np.random.rand(3,4)

array([[0.13478847, 0.59472326, 0.97821597, 0.08861251],
       [0.29394091, 0.23904398, 0.51661166, 0.04597103],
       [0.26465872, 0.67136671, 0.78927019, 0.36441934]])

In [22]:
r =np.loadtxt('somedata.txt',dtype = str)
r

array(['heloo', 'buddy'], dtype='<U5')

In [21]:
r =np.loadtxt('moredata.txt')
r

ValueError: could not convert string ',34,456,765,89' to float64 at row 0, column 2.

In [23]:
p= np.random.rand(3,4)
p

array([[0.11342968, 0.16679188, 0.01824974, 0.78856948],
       [0.27714299, 0.86507366, 0.52872064, 0.69292202],
       [0.05274132, 0.77317277, 0.20118524, 0.01749162]])

In [25]:
np.savetxt('new.txt',p,delimiter=',') # create new file

In [3]:
import numpy as np

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [29]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.random.rand(1)

array([0.31797437])

In [33]:
np.random.randn(25)

array([-1.18784148,  0.9276473 ,  0.27869318, -0.21242653,  0.30873478,
        0.16772937, -0.41357552, -0.37241186, -0.10459392,  0.93438143,
       -0.95557711, -0.7139711 ,  0.19797479,  1.90326929,  0.45117355,
       -0.25450333,  0.31322979,  0.01149267,  0.92287647, -0.39376929,
       -0.57382625, -0.10650424,  0.02958662, -0.45216199, -0.3487235 ])

In [34]:
np.arange(0.01,1.01,0.01).reshape(10,10) # inital,final,increment

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#  image topic
   #  image types
    #   1. true color image(RGB)  
    #   2.Grayscale
    #   3. binary
    #   4..CYAN
    #   5. hsv
    #   6. BGR

    #   for true pure color
    # (255,0,0)  for red color
    # (0,255,0)   for green color
    # (0,0,255)      for blue color
    # (255,255,255) for white color
    # (0,0,0)  for black color
      
    # Y=R+G
    # M=R+B
    # C=G+B
      
    #    for more information about color use "color picker" in google.

    